### PR TITLE
custom user-data property

### PR DESCRIPTION
**Pull request by jcyuan**
reopen the closed #80 (test report in it), because after a few days i feel this one is more convinent then an integer field, but anyway you decide, sir.

guess CI check will fail because of the ES5 option in the tsconfig.json.

### CODE REVIEW

**Comment by jcyuan** [comment]
ok, CI failed as i guessed. (used `Map`, ES6 required)

check what we discussed in #81 out, personally i think ES6 won't bring compat issue, because:

1, the current build of `rapier.es.js` needs a browser which supports es module import, and,
https://caniuse.com/?search=es%20module
such browsers are more newer then those which support ES6. (https://caniuse.com/?search=es6)

2, WebAssembly support:
https://caniuse.com/?search=webassembly
the same, higher requirement on browser then ES6. (https://caniuse.com/?search=es6)

3, the JS output with ES6 version is more effeicent then ES5.

but anyway, i don't know, maybe need some feedback from Rapier users first.

**Comment by alexandernanberg** [comment]
Hmm I'm wondering if it's worth supporting this natively in the lib. It's relatively easy to do in user land this with `Map<handle, metadata>` and there might be performance implications of adding this. I found this [talk](https://vimeo.com/649009599) really interesting but not sure how much of this translates to JS

**Comment by jcyuan** [comment]
> Hmm I'm wondering if it's worth supporting this natively in the lib. It's relatively easy to do in user land this with `Map<handle, metadata>` and there might be performance implications of adding this. I found this [talk](https://vimeo.com/649009599) really interesting but not sure how much of this translates to JS

no, it won't affect performance, because it won't deal with Rust. yes as you said, user can add their own user-data map in their logic, but actually this should be part of the lib because i think most of the dev users need it.

btw, do you think upgrade to ES6 compiling will affect something or not?

**Comment by alexandernanberg** [comment]
> no, it won't affect performance

The TLDR of the talk is to keep memory usage as low as possible, so it fits in CPU cache instead of memory which improves perf quite a bit. But yeah, don't feel like I understand enough of the internals yet to say if it makes a difference

> btw, do you think upgrade to ES6 compiling will affect something or not?

Hard to say, but IMO it's fine. Especially since it's a pre-release/alpha. If it breaks for a consumer for whatever reason they can add the needed polyfill or configure their compiler to also compile the Rapier pkg

**Comment by jcyuan** [comment]
> > no, it won't affect performance
> 
> The TLDR of the talk is to keep memory usage as low as possible, so it fits in CPU cache instead of memory which improves perf quite a bit. But yeah, don't feel like I understand enough of the internals yet to say if it makes a difference
> 
> > btw, do you think upgrade to ES6 compiling will affect something or not?
> 
> Hard to say, but IMO it's fine. Especially since it's a pre-release/alpha. If it breaks for a consumer for whatever reason they can add the needed polyfill or configure their compiler to also compile the Rapier pkg

good video! thanks for sharing.

**Comment by LeXXik** [comment]
I would prefer it to be in the user land. I agree that the feature itself is pretty common, but also not always mandatory. It is often needed for cases, when you are mapping a visual representation of an object in the renderer with the physical one in the physics world. On the other hand, there isn't always a visual representation. For server-authoritative physics in multiplayer games - there is no visual mesh. Also having it in user land, allows the dev to decide on the map structure, e.g. using Map vs WeakMap or other object that fits their design and configuration.

**Comment by jcyuan** [comment]
close this because there will be a plain `userData` field stub in PR #98 

thanks guys for discussing.

**Pull request closed without merging**
