### PR TITLE
Remove md5 and use xxHash128 for hashing algorithm in debug infos

### PR DESCRIPTION
**Pull request by Paulo-21**
#294 
Hello, i have choosen xxHash128 which is a non cryptographical hashing function and stay with the lenght of 128 bits to match the previous output with md5.
You can view the difference in term of performance bellow
Before :
[https://rapier.rs/demos3d/index.html](https://rapier.rs/demos3d/index.html)
[https://rapier.rs/demos2d/index.html](https://rapier.rs/demos2d/index.html)
After :
[https://pi-univers.fr/rapier.js/testbed3d/dist/](https://pi-univers.fr/rapier.js/testbed3d/dist/)
[https://pi-univers.fr/rapier.js/testbed2d/dist/](https://pi-univers.fr/rapier.js/testbed2d/dist/)

### CODE REVIEW

**Comment by Vrixyz** [comment]
I realize on the website, `md5` [is advertised](https://www.rapier.rs/docs/user_guides/javascript/determinism), so we might want to update that too for consistency.

But consider this outside of the scope of this PR, as this is outside of this repository + decision validation

**Review by sebcrozet — COMMENTED** [review]
Looks good, thanks! Why did the package.json of rapier need to be modified, considering that PR code changes are about the testbed only?

@Vrixyz I'm actually seeing the opposite: their build is slightly faster (on Android though). I think the main factor is that the official demos are still on rapier 0.12 whereas the new build is on 0.14.

**Comment by Vrixyz** [comment]
Thanks!

**Comment by Paulo-21** [comment]
Hello, does it will be backported to the website demo ?

**Comment by Vrixyz** [comment]
> Hello, does it will be backported to the website demo ?

Eventually, yes :+1: , but there's no strict schedule on doing so.

**Pull request merged**
