### PR TITLE
Enable building on windows

### LINKED ISSUE #184: error[E0277]: `*mut u8` cannot be shared between threads safely
Trying to build the project in IntelliJ IDEA but I run into this issue.

Am I doing something wrong? Do I need to use a specific version of rust or something?

### PR DESCRIPTION
**Pull request by firtoz**
Fixes #184

### CODE REVIEW

**Comment by Chargeuk** [comment]
Hi - I currently build Rapier & Rapier.js on Windows, will this pull request improve that in some way? Thanks

**Comment by firtoz** [comment]
@Chargeuk I am unsure... how do you build it? I had trouble, that's why I proposed the PR :D

**Comment by Chargeuk** [comment]
Hi @firtoz - Just loking at this now, I am able to build the rapier-compat on Windows without issue and this is what I normally use and build.

However, I forgot that I resorted to building rapier3d on WSL2 (as I don't usually do it) as it wasn't building on Windows, so it's great that you are resolving that issue.

Thanks 👍

**Comment by firtoz** [comment]
Another benefit is that it may eliminate the need to have the shell scripts for all platforms :) but I haven't tried what running the script will do on Linux or Mac.

**Comment by firtoz** [comment]
@Chargeuk good to hear :D

**Comment by firtoz** [comment]
@sebcrozet can you please take a look?

**Comment by sebcrozet** [comment]
Hey @firtoz! Thank you for making this PR and sorry for not viewing this earlier.
This is great start, it appears to work properly on MacOS too so I believe this will allow us to get rid of the build scripts like you suggested.

For this to be complete, I think that:
- The build function should take the version to build (2D or 3D) in parameter, so we can use the same scripts for both `rapier2d` and `rapier3d`. Right know it seems like we can only build the 3D version?
- We should be able to call each build step separately (build rust, build typescript, build doc). This is very useful for development.

It’s been some time since you worked on this, so I would understand if you don’t have the time to pick it up again now.

**Pull request closed without merging**
