### PR TITLE
chore: make compat build side-effect free

### PR DESCRIPTION
**Pull request by alexandernanberg**
**changes**

- Make `rapier-compat` builds side-effect free. They no longer modify files outside the compat directory. It has caught be off guard several times that building `rapier3d-compat` "breaks" the `rapier3d` pkg
- Easier dev setup for rapier packages by adding a root package.json with scripts and that testbeds can reference (this will be needed for a workspace setup anyway)
- Use local rapier2d and rapier3d version in testbeds

### CODE REVIEW

**Comment by alexandernanberg** [comment]
Hmm think I found some issues with the tests... let me have a look

**Comment by sebcrozet** [comment]
Thank you for this PR @alexandernanberg! Is this ready for review/merge or are there still issues with the tests?

**Comment by alexandernanberg** [comment]
@sebcrozet Yeah, dont' remember exactly what it was but can't reproduce any issues now!

**Comment by sebcrozet** [comment]
Perfect, thanks!

**Pull request merged**
