### PR TITLE
Add basic debug-render support

### PR DESCRIPTION
**Pull request by sebcrozet**
This adds a basic support for Rapier’s line-based debug-renderer. The rendering can’t be customized yet (customizations can be added in the future without a breaking change). Its usage with `world.debugRender()` is fairly straightforward. Here is an example of integration with THREE.js (for the 3D version). This needs to be run at each frame:

```js
if (!this.lines) {
    let material = new THREE.LineBasicMaterial({
        color: 0xffffff,
        vertexColors: THREE.VertexColors
    });
    let geometry =  new THREE.BufferGeometry();
    this.lines = new THREE.LineSegments(geometry, material);
    this.scene.add(this.lines);
}

let buffers = world.debugRender();
this.lines.geometry.setAttribute('position', new THREE.BufferAttribute(buffers.vertices, 3));
this.lines.geometry.setAttribute('color', new THREE.BufferAttribute(buffers.colors, 4));
```

Here is an example with PIXI.js (for the 2D version). This also needs to be run at each frame:
```js
if (!this.lines) {
    this.lines = new PIXI.Graphics();
    this.viewport.addChild(this.lines);
}
let buffers = world.debugRender();
let vtx = buffers.vertices;
let cls = buffers.colors;

this.lines.clear();

for (let i = 0; i < vtx.length / 4; i += 1) {
    let color = PIXI.utils.rgb2hex([cls[i * 8], cls[i * 8 + 1], cls[i * 8 + 2]]);
    this.lines.lineStyle(1.0, color, cls[i * 8 + 3], 0.5, true);
    this.lines.moveTo(vtx[i * 4], -vtx[i * 4 + 1]);
    this.lines.lineTo(vtx[i * 4 + 2], -vtx[i * 4 + 3]);
}
```

The testbed has been modified to apply the debug renderer on top of the meshes it currently already renders. This requires a simplification of the way the testbed works be removing the worker as well as the outdated code related to other physics engines. The large diff is mainly caused by the removed wasm resources (from ammo, physx, and box2d).

### CODE REVIEW

**Comment by ivanjermakov** [comment]
2D render example using plain CanvasRenderingContext2D:

```js
const drawDebug = (world: World, ctx: CanvasRenderingContext2D): void => {
    const buffers = world.debugRender()
    const vtx = buffers.vertices
    const cls = buffers.colors

    ctx.fillStyle = 'white'
    ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height)

    for (let i = 0; i < vtx.length / 4; i += 1) {
        const colorHex = [cls[i * 8], cls[i * 8 + 1], cls[i * 8 + 2]].map(n => {
            const clamped = Math.max(0, n)
            return Math.floor(clamped * 255).toString(16).padStart(2, '0');
        }).join('')

        const fromVec = {x: vtx[i * 4], y: -vtx[i * 4 + 1]}
        const toVec = {x: vtx[i * 4 + 2], y: -vtx[i * 4 + 3]}
        ctx.strokeStyle = '#' + colorHex
        ctx.lineWidth = 1
        ctx.beginPath()
        ctx.moveTo(fromVec.x, fromVec.y);
        ctx.lineTo(toVec.x, toVec.y);
        ctx.stroke()
    }
}
```

**Comment by 8Observer8** [comment]
Could anyone show how to draw colliders using Babylon.js? You can use this example: https://playground.babylonjs.com/#JL3MT8#1

starting-point-to-draw-colliders-using-rapier3d-and-babylonjs

**Comment by frankieali** [comment]
I'm trying to get things up and running with the debugRender in BabylonJS as well. I got this to work with your example
https://playground.babylonjs.com/#JL3MT8#2

**Comment by 8Observer8** [comment]
@frankieali Thank you very much! I copied your solution to another playgrounds and to GitHub repo to keep it because we don't know what can happen with Babylon's playground. I do this just in case for reservations. I created the topic: [Improve this debug rendering for the "rapier3d-compat" physics engine and Babylon.js if necessary](https://forum.babylonjs.com/t/improve-this-debug-rendering-for-the-rapier3d-compat-physics-engine-and-babylon-js-if-necessary/42283)

- PlayCode: https://playcode.io/1528902
- Plunker: https://plnkr.co/edit/dBHPCgYHa9fxnfO4?preview
- GitHub: https://github.com/8Observer8/debug-render-by-frankieali-rapier3dcompat-rollup-babylonjs-js This example contains an instruction how to build it with Rollup for Debug and Release modes. I use `importmap` with `rapier3D-compat` to make bundles with Rollup. This allows me to simply copy files to Playgrounds and save space on my laptop because I don't have to install NPM packages for every example.

debug-render-by-frankieali-babylonjs-js

How to use `importmap` with Babylon.js:

```html
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <title>Example</title>
</head>

<body>
    <ul>
        <li><a href="https://github.com/BabylonJS/Babylon.js/issues/14034">Issue</a>
        <li><a href="https://forum.babylonjs.com/t/problems-loading-babylon-via-es-modules/2031/39?u=8observer8">Topic</a>
    </ul>
    <br>
    <br>
    <canvas id="renderCanvas" width="400" height="400"></canvas>

    <!-- Since import maps are not yet supported by all browsers, its is
        necessary to add the polyfill es-module-shims.js -->
    <script async src="https://unpkg.com/es-module-shims@1.7.3/dist/es-module-shims.js"></script>

    <script type="importmap">
        {
            "imports": {
                "@babylonjs/core": "https://unpkg.com/@babylonjs/core@6.11.1",
                "@babylonjs/core/": "https://unpkg.com/@babylonjs/core@6.11.1/"
            }
        }
    </script>

    <script type="module">
        import { ArcRotateCamera } from "@babylonjs/core/Cameras/arcRotateCamera.js";
        import { Engine } from "@babylonjs/core/Engines/engine.js";
        import { MeshBuilder } from "@babylonjs/core/Meshes/meshBuilder.js";
        import { Scene } from "@babylonjs/core/scene.js";
        import { StandardMaterial } from "@babylonjs/core/Materials/standardMaterial.js";
        import { Vector3 } from "@babylonjs/core/Maths/math.vector.js";

        const canvas = document.getElementById("renderCanvas");
        const engine = new Engine(canvas, true);

        const scene = new Scene(engine);
        const sphere = MeshBuilder.CreateSphere("Sphere", { diameter: 2, segments: 32 }, scene);

        const camera = new ArcRotateCamera("Camera", -Math.PI / 2, Math.PI / 2.5, 15, new Vector3(0, 0, 0), scene);
        camera.setTarget(Vector3.Zero());
        camera.attachControl(canvas, true);

        engine.runRenderLoop(() => {
            scene.render();
        });
    </script>
</body>

</html>
```

**Comment by 8Observer8** [comment]
**Melon.js**

[Live demo](https://8observer8.github.io/webgl10-js/debug-drawer-rapier2d-melonjs-js/)

[GitHub repository](https://github.com/8Observer8/debug-drawer-rapier2d-melonjs-js)

Playgrounds:

- [Replit](https://replit.com/@8Observer8/Debug-drawer-of-colliders-using-Rapier2D-Melonjs-JS)
- [Plunker](https://plnkr.co/edit/jjDA2AYVyTIVi3hk?preview)
- [Glitch](https://glitch.com/edit/#!/furry-tiny-temple)

Topic and discussion:

- [Melon.js topic](https://melonjs.discourse.group/t/basic-examples-of-using-rapier2d-with-melon-js-in-javascript/58)
- [Melon.js discussion](https://github.com/melonjs/melonJS/discussions/1196)

debug-drawer-rapier2d-melonjs-js

**Pull request merged**
